services:
  mysql:
    image: mysql:8.0
    container_name: mysql-db
    restart: always
    command: --event_scheduler=ON
    environment:
      MYSQL_ROOT_PASSWORD: memelord1
      MYSQL_DATABASE: etudify
    ports:
      - "3307:3306"
    volumes:
      - mysql_data:/var/lib/mysql

  backend:
    build: ./back_end
    container_name: backend-api
    restart: always
    depends_on:
      - mysql
    ports:
      - "5070:8080"
    environment:
      ASPNETCORE_URLS: http://+:8080
      ConnectionStrings__DefaultConnection: Server=mysql;Port=3306;Database=etudify;User=root;Password=memelord1;

  frontend:
    build: ./front_end
    ports:
      - "8080:80"
    depends_on:
      - backend

volumes:
  mysql_data: